import { icon } from './icons.js'
import { escapeHtml } from '../lib/html.js'

const dates = [5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31]
const times = ['09:00','09:15','09:30','09:45','10:00','10:15','10:30','10:45','11:00']

export function renderProductPage(product, selection = {}) {
  if (!product) return `<section class="feature-page"><h1>Product not found</h1></section>`
  const selectedDate = Number(selection.date || 5)
  const selectedTime = selection.time || ''
  return `<section class="product-page"><div class="product-hero"><span class="product-badge">${escapeHtml(product.badge)}</span><h1>${escapeHtml(product.headline)}</h1><p>${escapeHtml(product.body)}</p><div class="hero-actions"><button type="button" class="outline-cta" data-action="scroll-calendar">Book a demo ${icon('external',17)}</button><button type="button" class="gradient-cta" data-action="start-trial">Start a free trial ${icon('chevron',18)}</button></div></div><section class="demo-calendar" id="demo-calendar"><div class="calendar-left"><div class="calendar-logo-mark"><img src="/assets/mediqo-logo.png" alt="MediQo" /></div><h2>Find a time to meet with MediQo</h2><div class="calendar-month">‹ <strong>October 2026</strong> ›</div><div class="weekdays"><span>MON</span><span>TUE</span><span>WED</span><span>THU</span><span>FRI</span><span>SAT</span><span>SUN</span></div><div class="calendar-days"><span class="empty"></span><span class="empty"></span><span class="empty"></span><span>1</span><span>2</span><span>3</span><span>4</span>${dates.map((date)=>`<button type="button" class="day ${selectedDate===date?'selected':''}" data-calendar-date="${date}">${date}</button>`).join('')}</div></div><div class="calendar-right"><div class="meeting-meta"><strong>Meeting location</strong><span>◉ Microsoft Teams</span></div><div class="meeting-meta"><strong>Meeting duration</strong><div class="duration-bar">30 mins</div></div><div class="time-heading"><strong>What time works best?</strong><span>Showing times for ${selectedDate} October 2026</span><small>UTC +11:00 Australian Eastern Time</small></div><div class="time-list">${times.map((time)=>`<button type="button" class="time ${selectedTime===time?'selected':''}" data-calendar-time="${time}">${time}</button>`).join('')}</div>${selectedTime?`<div class="slot-confirm"><strong>${icon('check',16)} Selected</strong><span>${selectedDate} October 2026 · ${selectedTime}</span><button class="primary-button" type="button" data-action="confirm-demo">Confirm demo time</button></div>`:''}</div></section></section>`
}
